version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=test
      - POSTGRES_ROOT_PASSWORD=password